### ISSUE TITLE
SQLite3 error is preventing the script from initializing

### ISSUE THREAD

**Issue by fakebenjay** [freedomofpress/trackthenews#16] opened 2018-07-19 18:45 UTC
Whenever I enter "trackthenews" into my console, I get a "sqlite3.OperationalError: cannot start a transaction within a transaction" error. I've put all of the RSS feeds I want into rssfeeds.json, with a few keywords in matchlist.txt. What is causing this error and how can it be fixed?

**Comment by jfilter** [comment] 2018-07-19 20:38
It has most likely to do with the sqlite exclusive connection I added.

https://github.com/freedomofpress/trackthenews/blob/master/trackthenews/core.py#L367
https://github.com/freedomofpress/trackthenews/blob/master/trackthenews/core.py#L431

What were your exact steps? Did you first run `trackthenews --config`?

**Comment by fakebenjay** [comment] 2018-07-19 20:40
yup, I ran `trackthenews --config`, entered the app keys and secrets, and then added the keywords and rss feeds

**Comment by jfilter** [comment] 2018-07-19 20:58
I just set it up again from scratch without any issues on my mac. You aren't doing something with the database file, right? On what OS are you setting it up?

It's hard for me to debug it remotely. I guess we need more tests. :/

**Comment by fakebenjay** [comment] 2018-07-19 21:00
I'm using MacOS Sierra. I haven't deliberately done anything to the database file, but it might be doing something automatically?

**Comment by jfilter** [comment] 2018-07-19 21:04
What is the version of your sqlite?

```
sqlite3 --version
3.23.1 2018-04-10 17:39:29 4bb2294022060e61de7da5c227a69ccd846ba330e31626ebcd59a94efd148b3b
```

**Comment by fakebenjay** [comment] 2018-07-19 21:18
`3.16.0 2016-11-04 19:09:39 0e5ffd9123d6d2d2b8f3701e8a73cc98a3a7ff5f`

**Comment by jfilter** [comment] 2018-07-19 21:22
Okay, try updating it to the latest version and let's see if it works then.

**Comment by fakebenjay** [comment] 2018-07-20 16:22
Still fruitless

**Comment by thisisparker** [comment] 2018-07-23 15:19
Hi @fakebenjay, sorry to hear you're having issues. I also haven't been able to reproduce this problem but let's see if we can get to the bottom of it. Just so I know where we're at: can you confirm that there's a `trackthenews.db` in the `ttn-config` folder? And then, if there is, can you run `sqlite3 trackthenews.db` and send the output of `.schema`? Thanks!

**Comment by fakebenjay** [comment] 2018-07-23 18:54
`trackthenews.db` is indeed in that folder, and there is no output when I enter `.schema`

**Comment by thisisparker** [comment] 2018-07-23 19:07
That is interesting! Given that neither @jfilter nor I can repro the specific issue, maybe we can just see if it works if you manually add in the schema? Try running `sqlite3 trackthenews.db` again and then paste this whole thing in:
```sql
CREATE TABLE articles (
            id          integer primary key autoincrement not null,
            title       text,
            outlet      text,
            url         text,
            tweeted     boolean,
            recorded_at datetime
        );
```

And then maybe things will work for you?

**Comment by fakebenjay** [comment] 2018-07-23 19:15
Actually, I'm afraid I was mistaken with that last comment. Sorry for the confusion I ran `sqlite3 trackthenews.db` from the wrong directory. When I run that command from `ttnconfig`, I get

`CREATE TABLE articles (
            id          integer primary key autoincrement not null,
            title       text,
            outlet      text,
            url         text,
            tweeted     boolean,
            recorded_at datetime
        );
CREATE TABLE sqlite_sequence(name,seq);`

**Comment by thisisparker** [comment] 2018-07-23 19:42
Hmmmm what's that second `CREATE` statement doing there! Can you try deleting the .db file and just running it again, in case it has to do with creating a new database under the old version? The script should be able to just detect that the database is missing and replace it with a new one.

**Comment by fakebenjay** [comment] 2018-07-23 20:02
I tried that and it didn't work, however, it is worth noting that when I do `CREATE TABLE articles` again, it also automatically adds `CREATE TABLE sqlite_sequence(name,seq)` as well

**Comment by thisisparker** [comment] 2018-07-23 20:24
Ok thanks for bearing with me on this and trying out some weird stuff. Could you creating the `articles` table but this time WITHOUT the `autoincrement`? Everything else can be there.

**Comment by fakebenjay** [comment] 2018-07-23 20:41
It didn't create the second `CREATE TABLE` but it still doesn't work

**Comment by thisisparker** [comment] 2018-07-23 20:52
Oooh, new promising lead. What version of Python are you attempting to run this with? It looks like there was a [similar error](https://bugs.python.org/issue28518) in some releases of 3.6 and 3.7. @jfilter is using 2.7 and I am using 3.5.2, so maybe that's why we can't repro?

**Comment by fakebenjay** [comment] 2018-07-23 20:53
3.6.3!

**Comment by conorsch** [comment] 2018-07-23 20:58
Now we're getting somewhere! Thanks for your patience, @fakebenjay. :upside_down_face:

**Comment by thisisparker** [comment] 2018-07-23 21:11
Wow, I've never been so excited to hit an `OperationalError`! I can officially reproduce this bug in python3.6.5.

I am going to see if removing the EXCLUSIVE transaction business fixes the problem, and if so I'll do a point upgrade. In the meantime, it is probably the case that running in 2.7 or 3.5 will solve your immediate problem, @fakebenjay.

**Comment by fakebenjay** [comment] 2018-07-23 21:11
I'll try it out, thank you!

**Comment by thisisparker** [comment] 2018-07-23 21:40
OK I'm pretty sure this is fixed with #18, which should also be available on pypi. `pip install -U trackthenews` should get you `0.1.9.2`, which in my testing with 3.6 should work! Please let me know :)

**Comment by thisisparker** [comment] 2018-08-03 14:04
Unless you're still having problems, I'm going to close this one as resolved!

**Closed by thisisparker** 2018-08-03 14:04 UTC

**Comment by gradywoodruff** [comment] 2018-12-04 15:42
I ran into this issue running track the news on python 3.6.0, but did not run into this issue using 3.6.1

**Comment by thisisparker** [comment] 2018-12-04 16:03
Interesting. I can't find anything in the [3.6.1 changelog](https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-1-final) that would account for that. If it's working for you after the upgrade, I'm going to leave this closed but keep an eye on it.
